name: Publish Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  prepare-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'    

      - name: Install Dependencies
        run: npm install
        
      # TODO: version bump, check-in?
     
      - name: build
        run: npm run build
     
      - name: Copy lib to package
        run: cp -r ./lib/ ./package/

      - name: Copy core files  to package
        run: cp ./{CODE_OF_CONDUCT.md,Contributing.md,LICENSE,README.md,index.js,package.json} ./package/
 
      - name: Publish package to NPM
        run: npm publish package --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
